write_files:
  - content: |
      BOOTPROTO='dhcp'
      BROADCAST=''
      ETHTOOL_OPTIONS=''
      IPADDR=''
      MTU=''
      NAME='Ethernet Card 2'
      NETMASK=''
      NETWORK=''
      REMOTE_IPADDR=''
      STARTMODE='auto'
    path: /etc/sysconfig/network/ifcfg-eth1

runcmd:
  - [ sudo, wicked, ifup, eth1 ]

# Base package install
package_update: true
packages:
  - ceph-base
  - ceph-common
